In [2]:
import numpy as np

x1 = np.arange(9.0).reshape((3, 3))
print(x1)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


In [4]:
x2=np.array([(2,3,4),(5,6,7),(7,8,9)])
print(x2)

[[2 3 4]
 [5 6 7]
 [7 8 9]]


In [5]:
print(x2-x1)

[[ 2.  2.  2.]
 [ 2.  2.  2.]
 [ 1.  1.  1.]]
